# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 11:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('due', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countdowns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tomato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=50)),
                ('duration', models.DurationField(default=datetime.timedelta(0, 1500))),
                ('completed', models.DateField(default=datetime.date(2017, 11, 19))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomatoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
