# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 11:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomato',
            name='completed',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 11, 51, 23, 330028, tzinfo=utc)),
        ),
    ]
