# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20171119_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomato',
            name='completed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
